In [ ]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd 

In [84]:
df = pd.read_csv('../data/Energy-Level-data-n_squared.csv')

In [85]:
df.head()

n   n_2          Mass        Length        Energy
0  82  6724  4.408112e-27  4.541342e-10  4.950111e-21
1  90  8100  8.831660e-30  5.671194e-09  1.738895e-20
2  20   400  6.898412e-28  4.776738e-09  6.973328e-23
3  81  6561  5.346241e-27  7.519782e-09  1.470443e-23
4  79  6241  2.596695e-27  9.654848e-09  1.791172e-23

In [86]:
df['inv_mass'] = 1 / df['Mass']
df['inv_length_squared'] = 1 / (df['Length'] ** 2)

In [87]:
df

n   n_2          Mass        Length        Energy      inv_mass  \
0      82  6724  4.408112e-27  4.541342e-10  4.950111e-21  2.268545e+26   
1      90  8100  8.831660e-30  5.671194e-09  1.738895e-20  1.132290e+29   
2      20   400  6.898412e-28  4.776738e-09  6.973328e-23  1.449609e+27   
3      81  6561  5.346241e-27  7.519782e-09  1.470443e-23  1.870473e+26   
4      79  6241  2.596695e-27  9.654848e-09  1.791172e-23  3.851049e+26   
...    ..   ...           ...           ...           ...           ...   
49995  83  6889  6.118655e-27  3.156070e-09  7.473963e-23  1.634346e+26   
49996  43  1849  2.680577e-27  6.933590e-09  1.831243e-23  3.730540e+26   
49997  53  2809  6.854707e-28  9.308764e-09  4.896943e-23  1.458852e+27   
49998  66  4356  1.804412e-27  2.941562e-09  2.319927e-22  5.541970e+26   
49999  69  4761  9.289981e-27  5.646828e-09  1.278342e-23  1.076428e+26   

       inv_length_squared  
0            4.848770e+18  
1            3.109217e+16  
2            4.382653e+16  
3            1.768437e+16  
4            1.072776e+16  
...                   ...  
49995        1.003938e+17  
49996        2.080098e+16  
49997        1.154027e+16  
49998        1.155697e+17  
49999        3.136107e+16  

[50000 rows x 7 columns]

In [88]:
X  = df[['n', 'n_2', 'inv_mass', 'inv_length_squared']].values

y = df[['Energy']].values

In [89]:
X

array([[8.20000000e+01, 6.72400000e+03, 2.26854475e+26, 4.84877045e+18],
       [9.00000000e+01, 8.10000000e+03, 1.13228999e+29, 3.10921722e+16],
       [2.00000000e+01, 4.00000000e+02, 1.44960908e+27, 4.38265333e+16],
       ...,
       [5.30000000e+01, 2.80900000e+03, 1.45885153e+27, 1.15402701e+16],
       [6.60000000e+01, 4.35600000e+03, 5.54197003e+26, 1.15569733e+17],
       [6.90000000e+01, 4.76100000e+03, 1.07642844e+26, 3.13610680e+16]])

In [90]:
y

array([[4.95011056e-21],
       [1.73889482e-20],
       [6.97332788e-23],
       ...,
       [4.89694258e-23],
       [2.31992685e-22],
       [1.27834234e-23]])

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
X_train

array([[9.50000000e+01, 9.02500000e+03, 6.07871099e+27, 4.37030728e+16],
       [5.00000000e+00, 2.50000000e+01, 2.73480914e+26, 2.95251756e+16],
       [6.00000000e+01, 3.60000000e+03, 1.33798178e+26, 1.15597256e+16],
       ...,
       [8.00000000e+01, 6.40000000e+03, 3.53159270e+27, 6.94434358e+17],
       [7.10000000e+01, 5.04100000e+03, 2.28017963e+28, 6.58083887e+17],
       [9.40000000e+01, 8.83600000e+03, 9.29220081e+28, 5.32499872e+16]])

In [93]:
y_train

array([[1.38506178e-21],
       [2.21570322e-24],
       [5.09296917e-24],
       ...,
       [1.07674749e-20],
       [5.84696831e-20],
       [2.55263088e-20]])

In [94]:
scaler_X = StandardScaler()

X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.fit_transform(X_test)

In [95]:
scaler_y = StandardScaler()

y_train_scaled = scaler_y.fit_transform(y_train)
y_test_scaled = scaler_y.transform(y_test)

In [96]:
X_train_scaled[1].shape

(4,)

In [97]:
model = tf.keras.Sequential([
    tf.keras.Input(shape = (4,)),
    tf.keras.layers.Dense(128, activation='relu'), 
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1)
])

In [98]:
model.compile(
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.001),
    loss = tf.keras.losses.MeanSquaredError(),
    metrics = ['mae'] 
)

In [99]:
model.fit(X_train_scaled , y_train_scaled, epochs=1000)

Epoch 1/1000
1250/1250 [==============================] - 3s 3ms/step - loss: 0.5598 - mae: 0.1318
Epoch 2/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.3523 - mae: 0.0924
Epoch 3/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.2581 - mae: 0.0825
Epoch 4/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.2407 - mae: 0.0649
Epoch 5/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.1880 - mae: 0.0581
Epoch 6/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.2110 - mae: 0.0619
Epoch 7/1000
1250/1250 [==============================] - 2s 2ms/step - loss: 0.1215 - mae: 0.0468
Epoch 8/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.3284 - mae: 0.0544
Epoch 9/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.1506 - mae: 0.0438
Epoch 10/1000
1250/1250 [==============================] - 3s 2ms/step - loss: 0.1734 - mae: 0.0472
Epoch 11/

In [100]:
loss, mae = model.evaluate(X_test_scaled, y_test_scaled)
print(f"Test MSE: {loss}, Test MAE: {mae}")


313/313 [==============================] - 0s 1ms/step - loss: 0.0358 - mae: 0.0259
Test MSE: 0.03583982214331627, Test MAE: 0.025894150137901306


In [101]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_train_scaled)
r2 = r2_score(y_train_scaled, y_pred)
print(f"R²_train score: {r2}")

1250/1250 [==============================] - 1s 909us/step
R²_train score: 0.9430361604137695


In [102]:
from sklearn.metrics import r2_score

y_pred = model.predict(X_test_scaled)
r2 = r2_score(y_test_scaled, y_pred)
print(f"R²_train score: {r2}")


313/313 [==============================] - 0s 1ms/step
R²_train score: 0.9531040396364763
